export function Header() {
    return (
        <>
            <div>
                <span>Finance</span><span>Ledger</span>
            </div>
            <div>
                <nav>
                    <ul>
                        <li>
                            <div>Home</div>
                        </li>
                        <li>
                            <div>About</div>
                        </li>
                        <li>
                            <div>Cases</div>
                        </li>
                        <li>
                            <div>Blog</div>
                        </li>
                        <li>
                            <div>Contact</div>
                        </li>
                    </ul>
                </nav>
            </div>
        </>
    );
}